services:
  _defaults:
    autowire: true
    autoconfigure: true

  Grokhotov\DataMigration\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"

  _instanceof:
    Grokhotov\DataMigration\Contract\DataMigrationTransformerInterface:
      tags: ["grokhotov.migration.transformer"]

    Grokhotov\DataMigration\Contract\DataMigrationPostProcessorInterface:
      tags: ["grokhotov.migration.post_processor"]
